### ISSUE TITLE
Version in mvnrepository

### ISSUE THREAD

**Issue by bardware** [sylvainlaurent/JDBC-Performance-Logger#57]
Hi,

latest version of your software on [mvnrepository](http://mvnrepository.com/artifact/com.github.sylvainlaurent.jdbcperflogger/jdbc-perf-logger-gui) is the old 0.7.3.
Can you push 0.8?

**Comment by sylvainlaurent** [comment]
fixed with 0.8.1. I don't know what happened with the publication of 0.8.0 artefacts, sorry.

**Comment by sylvainlaurent** [comment]
note that it can take a couple of hours for the artefacts to appear in maven central. For the moment they are in the staging repository of https://oss.sonatype.org/#stagingRepositories

**Comment by sylvainlaurent** [comment]
I had made a mistake when releasing the artifact, it's now fixed and available in Central, e.g. https://repo1.maven.org/maven2/com/github/sylvainlaurent/jdbcperflogger/jdbc-perf-logger-driver/0.8.1/
