### ISSUE TITLE
java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by bardware** [sylvainlaurent/JDBC-Performance-Logger#59]
Hi,

I prepended my jdbc URL with `jdbcperflogger:` and set Driver class to `ch.sla.jdbcperflogger.driver.WrappingDriver`. I received error `java.sql.SQLException: No suitable driver` I assumed this was because the logger-driver.jar would not be found which I would not want to believe. I eventually found the stack trace:
```
"Error","ajp-nio-8016-exec-8","05/07/17","14:55:03","","No suitable driver"
java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at ch.sla.jdbcperflogger.driver.WrappingDriver.connect(WrappingDriver.java:118)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:748)
```

This was easy to resolve, I  appended to the file `jdbcperflogger.xml` I provided using `-Djdbcperflogger.config.location` switch. 
I wonder if you could improve the exception message. 
I would be nice if it not only read `No suitable driver` but would also inform that it refers to the underying JDBC driver.

I see in your [source](https://github.com/sylvainlaurent/JDBC-Performance-Logger/blob/master/jdbc-perf-logger-driver/src/main/java/ch/sla/jdbcperflogger/driver/WrappingDriver.java) you try to secure the call to the creation of the driver instance and catch possible exceptions, but as you see in my stack trace the code reaches line 118 and throws.

**Comment by sylvainlaurent** [comment]
good suggestion, fixed post 0.8.1
