### ISSUE TITLE
Provide a download link for the distribution ZIP

### ISSUE THREAD

**Issue by madness-inc** [sylvainlaurent/JDBC-Performance-Logger#62]
Hi,

currently there's no way for downloading the distribution zip directly.
(Although you can figure out the link to maven central: http://repo1.maven.org/maven2/com/github/sylvainlaurent/jdbcperflogger/jdbc-perf-logger-gui/0.8.2/jdbc-perf-logger-gui-0.8.2-distrib.zip)

It would ne nice if such a link could be provided, probably here:
https://github.com/sylvainlaurent/JDBC-Performance-Logger/releases
or in the readme.

Regards
Matthias

**Comment by sylvainlaurent** [comment]
I could add a link to maven central for each release. What do you think? I just added it for 0.8.2

**Comment by madness-inc** [comment]
Great! Maybe you could link to the "releases" also from the README?
Because there you just mention the distribution, but without telling were to find it.

**Comment by sylvainlaurent** [comment]
readme has been updated a while back
