### ISSUE TITLE
Incorrect "filled SQL" if comment in SQL contains "?"

### ISSUE THREAD

**Issue by sylvainlaurent** [sylvainlaurent/JDBC-Performance-Logger#65]
with Hibernate SQL comments enabled, the SQL statement starts with a comment that contains the JPA query, which may contains bound variables like `?1`, `?2`...
In such a case v0.8.2 tries to replace the `?` in the SQL comment which is incorrect.

**Comment by sylvainlaurent** [comment]
it would require to use ANTLR to correctly parse SQL statement...

**Comment by samyBadjoudj** [comment]
the pull request https://github.com/sylvainlaurent/JDBC-Performance-Logger/pull/71 should take care of that. Without implementing a full parser with tokens. 
It removes comments before letting the fillParameters method doing the job.

**Comment by sylvainlaurent** [comment]
fixed by merging PR #72
